name: JAVA CI
env:
  docker_username: ${{secrets.DOCKER_USERNAME}}
  docker_password: ${{secrets.DOCKER_PASSWORD}}
  GIT_COMMIT: ${{github.sha}}
on: push
jobs:
  Clone-down:
    name: Clown down repo
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone-down
        uses: actions/checkout@v2
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
  Build:
    needs: Clone-down
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: Build app
        run: chmod +x ci/build-app.sh && ci/build-app.sh
      - name: Test
        run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with: 
          name: code
          path: .
      - name: Upload code
        uses: actions/upload-artifact@v2
        with:
          name: code-binary
          path: app/build/libs/app-0.1-all.jar
  Docker-image:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Download repo
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: Download code
        uses: actions/download-artifact@v2
        with:
          name: code-binary
          path: app/build/libs/app-0.1-all.jar
      - name: Build docker
        run: chmod +x ci/build-docker.sh && ci/build-docker.sh
      - name: Push docker
        run: chmod +x ci/push-docker.sh && ci/push-docker.sh